export const authStyles = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  card: {
    background: "var(--panel)",
    border: "1px solid var(--border-light)",
    borderRadius: 12,
    padding: 32,
    width: 380,
    maxWidth: "100%",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 24,
  },
  brandText: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 600,
    fontSize: 15,
    color: "var(--text)",
  },
  h1: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 22,
    fontWeight: 700,
    margin: "0 0 4px 0",
    color: "var(--text)",
  },
  tagline: {
    fontSize: 13,
    color: "var(--muted)",
    margin: "0 0 20px 0",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontSize: 12,
    color: "var(--muted)",
  },
  input: {
    background: "var(--bg)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "10px 11px",
    color: "var(--text)",
    fontSize: 14,
    outline: "none",
  },
  button: {
    background: "var(--teal)",
    border: "none",
    color: "#06201d",
    padding: "11px 16px",
    borderRadius: 6,
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 14,
    marginTop: 4,
  },
  error: {
    color: "var(--red)",
    fontSize: 13,
  },
  footNote: {
    marginTop: 18,
    fontSize: 13,
    color: "var(--muted)",
  },
};
